# -*- coding: utf-8 -*-
"""Random_name_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlyeQEGkCYUcDsrYby3Y8KoG6vBsPTXX
"""

import nltk
nltk.download('names')

names = nltk.corpus.names

male_names = names.words('male.txt')
female_names = names.words('female.txt')

import streamlit as st
import random

st.title("Fictional Name Generator")

# Get user preference for names
name_type = st.radio(
    "Choose a name type:",
    ('Male', 'Female', 'Mix it up')
)

# Select and display names based on preference
if st.button('Generate Names'):
    selected_names = []
    if name_type == 'Male':
        selected_names = random.sample(male_names, 3)
    elif name_type == 'Female':
        selected_names = random.sample(female_names, 3)
    else: # Mix it up
        all_names = male_names + female_names
        selected_names = random.sample(all_names, 3)

    st.write("Here are your names:")
    st.write("Here are your names:")
    st.write(", ".join(selected_names))
